### ISSUE TITLE
v0.6.0 error: `rust-src` component not found

### ISSUE THREAD

**Issue by steveyko** [rust-osdev/cargo-xbuild#88]
I have updated from v0.5.35 to v0.6.0, and 'cargo xbuild' is now throwing 'error: `rust_src` component not found.'

My --target is aarch64-unknown-none-softfloat.

v0.5.35 does not throw that error for me.

Here's some relevant info that might be useful.

rustup 1.22.1
rustc 1.47.0-nightly (2020-07-26)
cargo 1.47.0-nightly (2020-07-23)

**Comment by phil-opp** [comment]
Version 0.6.0 requires the new rust directory layout, which is only available since nightly 2020-07-30. See https://github.com/rust-osdev/cargo-xbuild/pull/87 for more information. I just updated the Readme in https://github.com/rust-osdev/cargo-xbuild/commit/400592f7a206c55815525e3b5d01a6a0d3e2b012 to document this requirement.
